-- AlterTable
ALTER TABLE "Booking" ALTER COLUMN "carId" DROP NOT NULL;
ALTER TABLE "Booking" ALTER COLUMN "customerId" DROP NOT NULL;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "purpose" TEXT;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "guestName" TEXT;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "guestPhone" TEXT;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "lineUid" TEXT;
